---
stages:
- name: BUILD
  inputs:
  - type: git
    branch: ${REPO_BRANCH}
    service: ${REPO}
  triggers:
  - type: commit
  jobs:
  - name: Build
    type: builder
    build_type: shell
    script: |-
      #!/bin/bash
      ./.bluemix/pipeline-BUILD.sh
- name: DEPLOY
  inputs:
  - type: job
    stage: BUILD
    job: Build
  triggers:
  - type: stage
  properties:
  - name: PACKAGE_NAME
    value: ${PACKAGE_NAME}
    type: text
  - name: CLOUDANT_DATABASE
    value: ${CLOUDANT_DATABASE}
    type: text
  - name: OPENWHISK_AUTH
    value: ${OPENWHISK_AUTH}
    type: secure
  - name: BLUEMIX_API_KEY
    value: ${BLUEMIX_API_KEY}
  - name: CLUSTER_NAME
    value: ${CLUSTER_NAME}
  - name: CONTROLLER_SERVICE
    value: ""
    type: text
  jobs:
  - name: Deploy
    type: deployer
    target:
      region_id: ${REGION_ID}
      organization: ${ORG_NAME}
      space: ${SPACE_NAME}
      application: "not-used"
    script: |-
      #!/bin/bash
      . ./.bluemix/pipeline-DEPLOY-Kubernetes.sh
      ./.bluemix/pipeline-DEPLOY.sh
