---
stages:
- name: DEPLOY
  inputs:
  - type: git
    branch: ${REPO_BRANCH}
    service: ${REPO}
  triggers:
  - type: stage
  jobs:
  - name: Blue/Green Deploy
    type: deployer
    target:
      region_id: ${REGION_ID}
      organization: ${ORG_NAME}
      space: ${SPACE_NAME}
      application: ${CF_APP_NAME}
    script: |-
      #!/bin/bash
      . ./.bluemix/pipeline-BUILD-Kubernetes.sh
      ./.bluemix/pipeline-BUILD.sh
      cd dist
      ./.bluemix/pipeline-DEPLOY.sh
